---
- name: Create systemd service
  register: smart_metrics_service_config
  template:
    src: 'smart-metrics.service.j2'
    dest: '/lib/systemd/system/{{ smart_metrics_service_name }}.service'
    mode: 0644
  notify: reload systemd

- name: (Re)start service
  when: |
    smart_metrics_service_config.changed or
    smart_metrics_binary.changed
  service:
    name: '{{ smart_metrics_service_name }}.service'
    state: 'restarted'
    enabled: true
